language: rust

rust:
  - stable
  - beta
  - nightly

script:
  - set -e
  - cargo build
  - cargo test

jobs:
  include:
    - stage: lint
      rust: nightly
      install:
        - rustup component add clippy-preview
        - rustup component add rustfmt-preview
      script:
        - cargo clippy -- --deny clippy
        - cargo fmt --all -- --check

    - stage: deploy docs
      rust: stable
      if: branch = master
      script:
        - set -e
        - gpg --decrypt --cipher-algo AES256 --passphrase $DEPLOY_KEY_PASSWORD --batch .travis/deploy_key.gpg > .travis/deploy_key
        - chmod 400 .travis/deploy_key
        - cargo doc --no-deps --release
        - ci-scripts/deploy/gh-pages.sh target/doc git@github.com:fschillerg/libvplan.git flyingB0tat0 bot@baudisch.xyz $(pwd)/.travis/deploy_key
      addons:
        ssh_known_hosts: github.com
